# https://github.com/karlvr/openapi-generator-plus-generators/blob/main/packages/typescript-fetch-client/templates/README.hbs
packageName: Testing
npmName: "@oursprivacy/ingest-sdk"

# Generator type moved from bash script
generatorName: typescript-fetch

disallowAdditionalPropertiesIfNotPresent: false
licenseName: MIT
supportsES6: true
withSeparateModelsAndApi: true