// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import OursPrivacy from '@oursprivacy/server-sdk';

const client = new OursPrivacy({ baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010' });

describe('resource visitor', () => {
  // Prism tests are disabled
  test.skip('upsert: only required params', async () => {
    const responsePromise = client.visitor.upsert({ token: 'x', userProperties: {} });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('upsert: required and optional params', async () => {
    const response = await client.visitor.upsert({
      token: 'x',
      userProperties: {
        ad_id: 'ad_id',
        adset_id: 'adset_id',
        alart: 'alart',
        aleid: 'aleid',
        basis_cid: 'basis_cid',
        campaign_id: 'campaign_id',
        city: 'city',
        clickid: 'clickid',
        clid: 'clid',
        company_name: 'company_name',
        consent: { foo: 'string' },
        country: 'country',
        custom_properties: { foo: 'string' },
        date_of_birth: 'date_of_birth',
        dclid: 'dclid',
        email: 'email',
        epik: 'epik',
        external_id: 'external_id',
        fbc: 'fbc',
        fbclid: 'fbclid',
        fbp: 'fbp',
        first_name: 'first_name',
        gad_source: 'gad_source',
        gbraid: 'gbraid',
        gclid: 'gclid',
        gender: 'gender',
        im_ref: 'im_ref',
        ip: 'ip',
        irclickid: 'irclickid',
        is_bot: 'is_bot',
        job_title: 'job_title',
        last_name: 'last_name',
        li_fat_id: 'li_fat_id',
        msclkid: 'msclkid',
        ndclid: 'ndclid',
        phone_number: 'phone_number',
        qclid: 'qclid',
        rdt_cid: 'rdt_cid',
        referrer: 'referrer',
        referring_domain: 'referring_domain',
        sacid: 'sacid',
        sccid: 'sccid',
        sid: 'sid',
        state: 'state',
        ttclid: 'ttclid',
        twclid: 'twclid',
        user_agent: 'user_agent',
        user_agent_full_list: 'user_agent_full_list',
        utm_campaign: 'utm_campaign',
        utm_content: 'utm_content',
        utm_medium: 'utm_medium',
        utm_name: 'utm_name',
        utm_source: 'utm_source',
        utm_term: 'utm_term',
        wbraid: 'wbraid',
        zip: 'zip',
      },
      defaultProperties: {
        activeDuration: 0,
        ad_id: 'ad_id',
        adset_id: 'adset_id',
        alart: 'alart',
        aleid: 'aleid',
        basis_cid: 'basis_cid',
        browser_language: 'browser_language',
        browser_name: 'browser_name',
        browser_version: 'browser_version',
        campaign_id: 'campaign_id',
        clickid: 'clickid',
        clid: 'clid',
        cpu_architecture: 'cpu_architecture',
        current_url: 'current_url',
        dclid: 'dclid',
        device_model: 'device_model',
        device_type: 'device_type',
        device_vendor: 'device_vendor',
        duration: 0,
        encoding: 'encoding',
        engine_name: 'engine_name',
        engine_version: 'engine_version',
        epik: 'epik',
        fbc: 'fbc',
        fbclid: 'fbclid',
        fbp: 'fbp',
        fv: true,
        gad_source: 'gad_source',
        gbraid: 'gbraid',
        gclid: 'gclid',
        host: 'host',
        iframe: true,
        im_ref: 'im_ref',
        ip: 'ip',
        irclickid: 'irclickid',
        is_bot: 'is_bot',
        li_fat_id: 'li_fat_id',
        msclkid: 'msclkid',
        ndclid: 'ndclid',
        new_s: true,
        os_name: 'os_name',
        os_version: 'os_version',
        page_hash: 0,
        pathname: 'pathname',
        qclid: 'qclid',
        rdt_cid: 'rdt_cid',
        received_at: 'received_at',
        referrer: 'referrer',
        referring_domain: 'referring_domain',
        sacid: 'sacid',
        sccid: 'sccid',
        screen_height: 0,
        screen_width: 0,
        sessionCount: 0,
        sid: 'sid',
        sr: 'sr',
        title: 'title',
        ttclid: 'ttclid',
        twclid: 'twclid',
        uafvl: 'uafvl',
        user_agent: 'user_agent',
        utm_campaign: 'utm_campaign',
        utm_content: 'utm_content',
        utm_medium: 'utm_medium',
        utm_name: 'utm_name',
        utm_source: 'utm_source',
        utm_term: 'utm_term',
        version: 'version',
        wbraid: 'wbraid',
        webview: true,
      },
      email: 'x',
      externalId: 'x',
      userId: 'x',
    });
  });
});
