/* tslint:disable */
/* eslint-disable */
/**
 * Ours
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackRequestDefaultProperties } from './TrackRequestDefaultProperties';
import {
    TrackRequestDefaultPropertiesFromJSON,
    TrackRequestDefaultPropertiesFromJSONTyped,
    TrackRequestDefaultPropertiesToJSON,
    TrackRequestDefaultPropertiesToJSONTyped,
} from './TrackRequestDefaultProperties';
import type { IdentifyRequestUserProperties } from './IdentifyRequestUserProperties';
import {
    IdentifyRequestUserPropertiesFromJSON,
    IdentifyRequestUserPropertiesFromJSONTyped,
    IdentifyRequestUserPropertiesToJSON,
    IdentifyRequestUserPropertiesToJSONTyped,
} from './IdentifyRequestUserProperties';

/**
 * 
 * @export
 * @interface IdentifyRequest
 */
export interface IdentifyRequest {
    /**
     * The token for your Ours Privacy Source. You can find this in the Ours dashboard.
     * @type {string}
     * @memberof IdentifyRequest
     */
    token: string;
    /**
     * The Ours user id stored in local storage and cookies on your web properties. If userId is included in the request, we do not lookup the user by email or externalId.
     * @type {string}
     * @memberof IdentifyRequest
     */
    userId: string;
    /**
     * 
     * @type {IdentifyRequestUserProperties}
     * @memberof IdentifyRequest
     */
    userProperties: IdentifyRequestUserProperties;
    /**
     * 
     * @type {TrackRequestDefaultProperties}
     * @memberof IdentifyRequest
     */
    defaultProperties?: TrackRequestDefaultProperties | null;
}

/**
 * Check if a given object implements the IdentifyRequest interface.
 */
export function instanceOfIdentifyRequest(value: object): value is IdentifyRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('userProperties' in value) || value['userProperties'] === undefined) return false;
    return true;
}

export function IdentifyRequestFromJSON(json: any): IdentifyRequest {
    return IdentifyRequestFromJSONTyped(json, false);
}

export function IdentifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'userId': json['userId'],
        'userProperties': IdentifyRequestUserPropertiesFromJSON(json['userProperties']),
        'defaultProperties': json['defaultProperties'] == null ? undefined : TrackRequestDefaultPropertiesFromJSON(json['defaultProperties']),
    };
}

export function IdentifyRequestToJSON(json: any): IdentifyRequest {
    return IdentifyRequestToJSONTyped(json, false);
}

export function IdentifyRequestToJSONTyped(value?: IdentifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'userId': value['userId'],
        'userProperties': IdentifyRequestUserPropertiesToJSON(value['userProperties']),
        'defaultProperties': TrackRequestDefaultPropertiesToJSON(value['defaultProperties']),
    };
}

