/* tslint:disable */
/* eslint-disable */
/**
 * Ours
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User properties to associate with this user. The existing user properties will be updated. And all future events will have these properties associated with them.
 * @export
 * @interface IdentifyRequestUserProperties
 */
export interface IdentifyRequestUserProperties {
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    dateOfBirth?: string | null;
    /**
     * 
     * @type {any}
     * @memberof IdentifyRequestUserProperties
     */
    phoneNumber?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    state?: string | null;
    /**
     * 
     * @type {any}
     * @memberof IdentifyRequestUserProperties
     */
    zip?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    jobTitle?: string | null;
    /**
     * The IP address of the user
     * @type {string}
     * @memberof IdentifyRequestUserProperties
     */
    ip?: string | null;
}

/**
 * Check if a given object implements the IdentifyRequestUserProperties interface.
 */
export function instanceOfIdentifyRequestUserProperties(value: object): value is IdentifyRequestUserProperties {
    return true;
}

export function IdentifyRequestUserPropertiesFromJSON(json: any): IdentifyRequestUserProperties {
    return IdentifyRequestUserPropertiesFromJSONTyped(json, false);
}

export function IdentifyRequestUserPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentifyRequestUserProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'dateOfBirth': json['date_of_birth'] == null ? undefined : json['date_of_birth'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zip': json['zip'] == null ? undefined : json['zip'],
        'country': json['country'] == null ? undefined : json['country'],
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'companyName': json['company_name'] == null ? undefined : json['company_name'],
        'jobTitle': json['job_title'] == null ? undefined : json['job_title'],
        'ip': json['ip'] == null ? undefined : json['ip'],
    };
}

export function IdentifyRequestUserPropertiesToJSON(json: any): IdentifyRequestUserProperties {
    return IdentifyRequestUserPropertiesToJSONTyped(json, false);
}

export function IdentifyRequestUserPropertiesToJSONTyped(value?: IdentifyRequestUserProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'gender': value['gender'],
        'date_of_birth': value['dateOfBirth'],
        'phone_number': value['phoneNumber'],
        'city': value['city'],
        'state': value['state'],
        'zip': value['zip'],
        'country': value['country'],
        'external_id': value['externalId'],
        'company_name': value['companyName'],
        'job_title': value['jobTitle'],
        'ip': value['ip'],
    };
}

