/* tslint:disable */
/* eslint-disable */
/**
 * Ours
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Track200Response
 */
export interface Track200Response {
    /**
     * 
     * @type {boolean}
     * @memberof Track200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the Track200Response interface.
 */
export function instanceOfTrack200Response(value: object): value is Track200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function Track200ResponseFromJSON(json: any): Track200Response {
    return Track200ResponseFromJSONTyped(json, false);
}

export function Track200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Track200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function Track200ResponseToJSON(json: any): Track200Response {
    return Track200ResponseToJSONTyped(json, false);
}

export function Track200ResponseToJSONTyped(value?: Track200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

