/* tslint:disable */
/* eslint-disable */
/**
 * Ours
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * These properties are used throughout the Ours app to pass known values onto destinations
 * @export
 * @interface TrackRequestDefaultProperties
 */
export interface TrackRequestDefaultProperties {
    /**
     * 
     * @type {boolean}
     * @memberof TrackRequestDefaultProperties
     */
    isBot?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    adId?: string | null;
    /**
     * The character encoding of the page. Ex: UTF-8
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    encoding?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    browserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    browserVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    cpuArchitecture?: string | null;
    /**
     * "mobile" | "tablet" | "console" | "smarttv" | "wearable" | "xr" | "embedded"
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    deviceType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    deviceModel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    deviceVendor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    engineName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    engineVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    osName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    osVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    browserLanguage?: string | null;
    /**
     * The full url (including query params) of the current page
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    currentUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackRequestDefaultProperties
     */
    webview?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof TrackRequestDefaultProperties
     */
    iframe?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof TrackRequestDefaultProperties
     */
    sessionCount?: number | null;
    /**
     * The active time in milliseconds that the user had this tab active
     * @type {number}
     * @memberof TrackRequestDefaultProperties
     */
    activeDuration?: number | null;
    /**
     * The time in milliseconds since the page was loaded // script was loaded
     * @type {number}
     * @memberof TrackRequestDefaultProperties
     */
    duration?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    epik?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    sacid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    fbc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    fbclid?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackRequestDefaultProperties
     */
    fbclidCreationTime?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    fbp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    gadSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    gbraid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    gcId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    gclid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    rdtCid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    host?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    ip?: string | null;
    /**
     * The MSCLKID that led to the conversion (see below for click ID information). The MSCLKID is a GUID (32 characters) that is unique for each ad click
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    msclkid?: string | null;
    /**
     * The LinkedIn Fat ID that led to the conversion (see below for click ID information). The Fat ID is a GUID (32 characters) that is unique for each ad click
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    liFatId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    pathname?: string | null;
    /**
     * The referrer URL of the current page
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    referrer?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackRequestDefaultProperties
     */
    screenHeight?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrackRequestDefaultProperties
     */
    screenWidth?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    userAgent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    userAgentFullList?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    utmCampaign?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    utmContent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    utmMedium?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    utmName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    ttclid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    utmSource?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    utmTerm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    version?: string | null;
    /**
     * ?wbraid=1
     * @type {string}
     * @memberof TrackRequestDefaultProperties
     */
    wbraid?: string | null;
}

/**
 * Check if a given object implements the TrackRequestDefaultProperties interface.
 */
export function instanceOfTrackRequestDefaultProperties(value: object): value is TrackRequestDefaultProperties {
    return true;
}

export function TrackRequestDefaultPropertiesFromJSON(json: any): TrackRequestDefaultProperties {
    return TrackRequestDefaultPropertiesFromJSONTyped(json, false);
}

export function TrackRequestDefaultPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackRequestDefaultProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'isBot': json['is_bot'] == null ? undefined : json['is_bot'],
        'adId': json['ad_id'] == null ? undefined : json['ad_id'],
        'encoding': json['encoding'] == null ? undefined : json['encoding'],
        'browserName': json['browser_name'] == null ? undefined : json['browser_name'],
        'browserVersion': json['browser_version'] == null ? undefined : json['browser_version'],
        'cpuArchitecture': json['cpu_architecture'] == null ? undefined : json['cpu_architecture'],
        'deviceType': json['device_type'] == null ? undefined : json['device_type'],
        'deviceModel': json['device_model'] == null ? undefined : json['device_model'],
        'deviceVendor': json['device_vendor'] == null ? undefined : json['device_vendor'],
        'engineName': json['engine_name'] == null ? undefined : json['engine_name'],
        'engineVersion': json['engine_version'] == null ? undefined : json['engine_version'],
        'osName': json['os_name'] == null ? undefined : json['os_name'],
        'osVersion': json['os_version'] == null ? undefined : json['os_version'],
        'browserLanguage': json['browser_language'] == null ? undefined : json['browser_language'],
        'currentUrl': json['current_url'] == null ? undefined : json['current_url'],
        'webview': json['webview'] == null ? undefined : json['webview'],
        'iframe': json['iframe'] == null ? undefined : json['iframe'],
        'sessionCount': json['sessionCount'] == null ? undefined : json['sessionCount'],
        'activeDuration': json['activeDuration'] == null ? undefined : json['activeDuration'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'epik': json['epik'] == null ? undefined : json['epik'],
        'sacid': json['sacid'] == null ? undefined : json['sacid'],
        'fbc': json['fbc'] == null ? undefined : json['fbc'],
        'fbclid': json['fbclid'] == null ? undefined : json['fbclid'],
        'fbclidCreationTime': json['fbclid_creation_time'] == null ? undefined : json['fbclid_creation_time'],
        'fbp': json['fbp'] == null ? undefined : json['fbp'],
        'gadSource': json['gad_source'] == null ? undefined : json['gad_source'],
        'gbraid': json['gbraid'] == null ? undefined : json['gbraid'],
        'gcId': json['gc_id'] == null ? undefined : json['gc_id'],
        'gclid': json['gclid'] == null ? undefined : json['gclid'],
        'rdtCid': json['rdt_cid'] == null ? undefined : json['rdt_cid'],
        'host': json['host'] == null ? undefined : json['host'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'msclkid': json['msclkid'] == null ? undefined : json['msclkid'],
        'liFatId': json['li_fat_id'] == null ? undefined : json['li_fat_id'],
        'pathname': json['pathname'] == null ? undefined : json['pathname'],
        'referrer': json['referrer'] == null ? undefined : json['referrer'],
        'screenHeight': json['screen_height'] == null ? undefined : json['screen_height'],
        'screenWidth': json['screen_width'] == null ? undefined : json['screen_width'],
        'title': json['title'] == null ? undefined : json['title'],
        'userAgent': json['user_agent'] == null ? undefined : json['user_agent'],
        'userAgentFullList': json['user_agent_full_list'] == null ? undefined : json['user_agent_full_list'],
        'utmCampaign': json['utm_campaign'] == null ? undefined : json['utm_campaign'],
        'utmContent': json['utm_content'] == null ? undefined : json['utm_content'],
        'utmMedium': json['utm_medium'] == null ? undefined : json['utm_medium'],
        'utmName': json['utm_name'] == null ? undefined : json['utm_name'],
        'ttclid': json['ttclid'] == null ? undefined : json['ttclid'],
        'utmSource': json['utm_source'] == null ? undefined : json['utm_source'],
        'utmTerm': json['utm_term'] == null ? undefined : json['utm_term'],
        'version': json['version'] == null ? undefined : json['version'],
        'wbraid': json['wbraid'] == null ? undefined : json['wbraid'],
    };
}

export function TrackRequestDefaultPropertiesToJSON(json: any): TrackRequestDefaultProperties {
    return TrackRequestDefaultPropertiesToJSONTyped(json, false);
}

export function TrackRequestDefaultPropertiesToJSONTyped(value?: TrackRequestDefaultProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_bot': value['isBot'],
        'ad_id': value['adId'],
        'encoding': value['encoding'],
        'browser_name': value['browserName'],
        'browser_version': value['browserVersion'],
        'cpu_architecture': value['cpuArchitecture'],
        'device_type': value['deviceType'],
        'device_model': value['deviceModel'],
        'device_vendor': value['deviceVendor'],
        'engine_name': value['engineName'],
        'engine_version': value['engineVersion'],
        'os_name': value['osName'],
        'os_version': value['osVersion'],
        'browser_language': value['browserLanguage'],
        'current_url': value['currentUrl'],
        'webview': value['webview'],
        'iframe': value['iframe'],
        'sessionCount': value['sessionCount'],
        'activeDuration': value['activeDuration'],
        'duration': value['duration'],
        'epik': value['epik'],
        'sacid': value['sacid'],
        'fbc': value['fbc'],
        'fbclid': value['fbclid'],
        'fbclid_creation_time': value['fbclidCreationTime'],
        'fbp': value['fbp'],
        'gad_source': value['gadSource'],
        'gbraid': value['gbraid'],
        'gc_id': value['gcId'],
        'gclid': value['gclid'],
        'rdt_cid': value['rdtCid'],
        'host': value['host'],
        'ip': value['ip'],
        'msclkid': value['msclkid'],
        'li_fat_id': value['liFatId'],
        'pathname': value['pathname'],
        'referrer': value['referrer'],
        'screen_height': value['screenHeight'],
        'screen_width': value['screenWidth'],
        'title': value['title'],
        'user_agent': value['userAgent'],
        'user_agent_full_list': value['userAgentFullList'],
        'utm_campaign': value['utmCampaign'],
        'utm_content': value['utmContent'],
        'utm_medium': value['utmMedium'],
        'utm_name': value['utmName'],
        'ttclid': value['ttclid'],
        'utm_source': value['utmSource'],
        'utm_term': value['utmTerm'],
        'version': value['version'],
        'wbraid': value['wbraid'],
    };
}

